apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: helloApp
  region: us-west-2

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    amiFamily: AmazonLinux2
    minSize: 2
    maxSize: 3
    volumeSize: 70
    ssh:
      allow: true
      publicKeyName: udacity