version: 2.1

orbs:
  docker: circleci/docker@2.0.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Create environment 
          command: |
            #!/bin/bash
            make setup_no_source
            source ~/.capstoneProj/bin/activate 
      - run : 
          name: Install dependencies
          command: |
            make python_install    
      - run:
          name: Run lint
          command: |
            source ~/.capstoneProj/bin/activate 
            make lint 
  
  
  
  Update:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Installing kube and dependencies
          command: |
            make setup_no_source
            source ~/.capstoneProj/bin/activate 
      - run:
          name: Update EKS lint
          command: |
            make setup_no_source
            source ~/.capstoneProj/bin/activate 
            make rolling_update 


workflows:
  default:
    jobs:
      - build
      - docker/publish:
          matrix:
            parameters:
              image: [$DOCKER_LOGIN/helloapp]
              path: [helloapp]
              docker-context: [helloapp]
              deploy: [true]
              update-description: [true]    
          requires: [build]