version: 2.1

orbs:
  docker: circleci/docker@2.0.1

jobs:
  build:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Create environment 
          command: |
            make setup
            ../ ~/.capstoneProj/bin/activate 
      - run : 
          name: Install dependencies
          command: |
            make python_install    
      - run:
          name: Run lint
          command: |
            source ~/.capstoneProj/bin/activate 
            make lint 

workflows:
  default:
    jobs:
      - build
      - docker/publish:
          matrix:
            parameters:
              image: [$DOCKER_LOGIN/helloapp]
              path: [helloapp]
              docker-context: [helloapp]
              deploy: [true]
              tag: ['$(<helloapp/VERSION.txt)', 'latest']
              update-description: [true]    
          requires: [build]